<?php
// ═══════════════════════════════════════════════════════
//  ProfeBot — Servidor local PHP
//  Uso: php -S localhost:8080
//  Abrir: http://localhost:8080/profebot.php
// ═══════════════════════════════════════════════════════

// Autoloader (Monolog for logs). vendor/ is generated by `composer install`.
@require_once __DIR__.'/vendor/autoload.php';

use Monolog\Logger;
use Monolog\Handler\StreamHandler;

// ── CACHE DE PREGUNTAS ──
define('CACHE_FILE', __DIR__.'/question_cache.json');
define('CACHE_MAX_PER_KEY', 50);

// ── VERSION ──
function pb_version()
{
    static $v = null;
    if ($v !== null) {
        return $v;
    }
    $f = __DIR__.'/VERSION';
    if (is_file($f)) {
        $v = trim(file_get_contents($f));
        if ($v !== '') {
            return $v;
        }
    }
    $v = 'dev';
    return $v;
}

// ── LOGGER ──
function pb_log()
{
    static $logger = null;
    if ($logger !== null) {
        return $logger;
    }
    if (!class_exists('Monolog\\Logger')) {
        $logger = false; // marker: Monolog not available
        return $logger;
    }
    $logger = new Logger('profebot');
    $logger->pushHandler(new StreamHandler('php://stderr', Logger::DEBUG));
    return $logger;
}

function pb_log_warn($msg, array $ctx = [])
{
    $l = pb_log();
    if ($l) {
        $l->warning($msg, $ctx);
    } else {
        error_log('[WARN] '.$msg.' '.json_encode($ctx, JSON_UNESCAPED_UNICODE));
    }
}

function pb_log_error($msg, array $ctx = [])
{
    $l = pb_log();
    if ($l) {
        $l->error($msg, $ctx);
    } else {
        error_log('[ERROR] '.$msg.' '.json_encode($ctx, JSON_UNESCAPED_UNICODE));
    }
}

function pb_log_info($msg, array $ctx = [])
{
    $l = pb_log();
    if ($l) {
        $l->info($msg, $ctx);
    } else {
        error_log('[INFO] '.$msg.' '.json_encode($ctx, JSON_UNESCAPED_UNICODE));
    }
}

// ── MATERIALES (lectura server-side; nunca expuestos por HTTP) ──
define('MATERIALS_DIR', __DIR__.'/materiales');
define('MATERIAL_MAX_CHARS', 3000);

$DEFAULT_MATERIALS = [
    ['file' => 'leng_libro_antiguo.txt', 'name' => 'Libro Lengua (antiguo)', 'subj' => 'leng', 'grade' => '1ro'],
    ['file' => 'leng_libro.txt', 'name' => '¡A leer! 1er. Grado', 'subj' => 'leng', 'grade' => '1ro'],
    ['file' => 'leng_cuaderno.txt', 'name' => 'Cuaderno Escritura', 'subj' => 'leng', 'grade' => '1ro'],
    ['file' => 'mat_libro_antiguo.txt', 'name' => 'Libro Matemática (antiguo)', 'subj' => 'mat', 'grade' => '1ro'],
    ['file' => 'mat_libro.txt', 'name' => 'Matemática 1er. Grado', 'subj' => 'mat', 'grade' => '1ro'],
    ['file' => 'mat_cuaderno.txt', 'name' => 'Cuaderno Matemática', 'subj' => 'mat', 'grade' => '1ro'],
    ['file' => 'preesc_mat_conjuntos.txt', 'name' => 'Nociones Matemáticas: Conjuntos (5to)', 'subj' => 'mat', 'grade' => 'preesc'],
    ['file' => 'preesc_mat_problemas.txt', 'name' => 'Solución de Problemas Sencillos (6to)', 'subj' => 'mat', 'grade' => 'preesc'],
    ['file' => 'preesc_mat_operaciones.txt', 'name' => 'Operaciones Combinadas de Conjuntos (6to)', 'subj' => 'mat', 'grade' => 'preesc'],
    ['file' => 'preesc_mat_longitudes.txt', 'name' => 'Trabajo con Longitudes (6to)', 'subj' => 'mat', 'grade' => 'preesc'],
    ['file' => 'preesc_len_fonico.txt', 'name' => 'Cuaderno de Análisis Fónico (6to)', 'subj' => 'len', 'grade' => 'preesc'],
    ['file' => 'preesc_len_cuentos.txt', 'name' => 'Cuentos para el 5to año de vida', 'subj' => 'len', 'grade' => 'preesc'],
    ['file' => 'preesc_len_poesias.txt', 'name' => 'Poesías para el 5to año de vida', 'subj' => 'len', 'grade' => 'preesc'],
    ['file' => 'preesc_len_adivinanzas.txt', 'name' => 'Adivinanzas 5to y 6to año', 'subj' => 'len', 'grade' => 'preesc'],
    ['file' => 'preesc_len_fabulas.txt', 'name' => 'Fábulas para el 5to año de vida', 'subj' => 'len', 'grade' => 'preesc'],
    ['file' => 'preesc_len_6to_cuentos.txt', 'name' => 'Cuentos para el 6to año de vida', 'subj' => 'len', 'grade' => 'preesc'],
    ['file' => 'preesc_len_6to_poesias.txt', 'name' => 'Poesías para el 6to año de vida', 'subj' => 'len', 'grade' => 'preesc'],
    ['file' => 'preesc_len_6to_fabulas.txt', 'name' => 'Fábulas para el 6to año de vida', 'subj' => 'len', 'grade' => 'preesc'],
    ['file' => 'preesc_len_trabalenguas.txt', 'name' => 'Trabalenguas para el 6to año de vida', 'subj' => 'len', 'grade' => 'preesc'],
];

function build_default_ctx($grade, $subj, $materials)
{
    $matches = array_values(array_filter($materials, function ($m) use ($grade, $subj) {
        return $m['grade'] === $grade && $m['subj'] === $subj;
    }));
    if (empty($matches)) return '';
    $ctx = "\n\n=== MATERIALES DEL CURRÍCULO ===\nUsá este contenido como guía para el nivel y estilo de las preguntas. Si el tema no aparece en el material, generá la pregunta igualmente basándote en el objetivo.\n\n";
    $i = 1;
    foreach ($matches as $m) {
        $path = MATERIALS_DIR.'/'.$m['file'];
        if (!is_readable($path)) continue;
        $raw = @file_get_contents($path);
        if ($raw === false) continue;
        $content = trim($raw);
        if (function_exists('mb_substr')) {
            $content = mb_substr($content, 0, MATERIAL_MAX_CHARS);
        } else {
            $content = substr($content, 0, MATERIAL_MAX_CHARS);
        }
        $ctx .= "--- $i: ".substr($m['name'], 0, 50)." ---\n$content\n\n";
        $i++;
    }
    return $ctx."=== FIN ===\n";
}

// Cargar .env si existe (local con php -S)
$CONFIG_KEYS = [];
if (file_exists(__DIR__ . '/.env')) {
    foreach (file(__DIR__ . '/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        if ($line[0] === '#' || strpos($line, '=') === false) continue;
        [$k, $v] = explode('=', $line, 2);
        putenv(trim($k) . '=' . trim($v));
    }
}
// Cargar config.php si existe (InfinityFree u otro hosting sin env vars)
@include __DIR__ . '/config.php';

function cache_read()
{
    if (!file_exists(CACHE_FILE)) {
        return [];
    }
    $raw = file_get_contents(CACHE_FILE);
    if ($raw === false || $raw === '') {
        return [];
    }
    $data = json_decode($raw, true);
    return is_array($data) ? $data : [];
}

function cache_write($data)
{
    $f = fopen(CACHE_FILE, 'c+');
    if (!$f) {
        return false;
    }
    flock($f, LOCK_EX);
    ftruncate($f, 0);
    rewind($f);
    fwrite($f, json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
    fflush($f);
    flock($f, LOCK_UN);
    fclose($f);
    return true;
}

// ── PROXY API: multi-proveedor con fallback automático ──
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $raw = file_get_contents('php://input');
    $data = json_decode($raw, true);

    // ── Cache actions ──
    if (isset($data['action'])) {
        header('Content-Type: application/json');
        header('Access-Control-Allow-Origin: *');

        if ($data['action'] === 'cache_get') {
            $key = isset($data['cache_key']) ? $data['cache_key'] : '';
            $exclude = isset($data['exclude']) ? $data['exclude'] : [];
            $cache = cache_read();
            $items = isset($cache[$key]) ? $cache[$key] : [];
            // Filter out already-asked questions
            $available = array_values(array_filter($items, function ($q) use ($exclude) {
                return !in_array($q['question'], $exclude);
            }));
            if (empty($available)) {
                echo json_encode(['cached' => false]);
            } else {
                // If fewer than 5 cached, 50% chance to skip cache and go to AI to grow variety
                if (count($items) < 5 && mt_rand(1, 100) <= 50) {
                    echo json_encode(['cached' => false]);
                } else {
                    $pick = $available[array_rand($available)];
                    echo json_encode(['cached' => true, 'question' => $pick]);
                }
            }
            exit;
        }

        if ($data['action'] === 'materials_meta') {
            $grade = isset($data['grade']) ? $data['grade'] : '';
            $list = array_values(array_filter($DEFAULT_MATERIALS, function ($m) use ($grade) {
                return !$grade || $m['grade'] === $grade;
            }));
            $out = array_map(function ($m) {
                return ['name' => $m['name'], 'subj' => $m['subj'], 'grade' => $m['grade']];
            }, $list);
            echo json_encode(['materials' => $out], JSON_UNESCAPED_UNICODE);
            exit;
        }

        if ($data['action'] === 'cache_save') {
            $key = isset($data['cache_key']) ? $data['cache_key'] : '';
            $question = isset($data['question']) ? $data['question'] : null;
            if (!$key || !$question) {
                echo json_encode(['saved' => false, 'error' => 'missing data']);
                exit;
            }
            $cache = cache_read();
            if (!isset($cache[$key])) {
                $cache[$key] = [];
            }
            $cache[$key][] = $question;
            // FIFO: keep max per key
            if (count($cache[$key]) > CACHE_MAX_PER_KEY) {
                $cache[$key] = array_slice($cache[$key], -CACHE_MAX_PER_KEY);
            }
            cache_write($cache);
            echo json_encode(['saved' => true]);
            exit;
        }
    }

    // Registro de proveedores
    $PROVIDERS = [
            'groq'   => [
                    'env'   => 'GROQ_API_KEY',
                    'build' => function ($data, $key) {
                        $body = ['model' => 'llama-3.3-70b-versatile', 'max_tokens' => 2048, 'messages' => []];
                        if (!empty($data['system'])) {
                            $body['messages'][] = ['role' => 'system', 'content' => $data['system']];
                        }
                        if (!empty($data['messages'])) {
                            foreach ($data['messages'] as $m) {
                                $body['messages'][] = ['role' => $m['role'], 'content' => $m['content']];
                            }
                        }
                        return [
                                'url'     => 'https://api.groq.com/openai/v1/chat/completions',
                                'headers' => ['Content-Type: application/json', 'Authorization: Bearer '.$key],
                                'body'    => json_encode($body),
                        ];
                    },
                    'parse' => function ($resp) {
                        $d = json_decode($resp, true);
                        $text = $d['choices'][0]['message']['content'] ?? null;
                        $err = $d['error']['message'] ?? null;
                        $usage = $d['usage'] ?? null;
                        return ['text' => $text, 'error' => $err, 'usage' => $usage];
                    },
            ],
            'claude' => [
                    'env'   => 'ANTHROPIC_API_KEY',
                    'build' => function ($data, $key) {
                        $body = ['model' => 'claude-sonnet-4-20250514', 'max_tokens' => 1024];
                        if (!empty($data['system'])) {
                            $body['system'] = $data['system'];
                        }
                        $body['messages'] = [];
                        if (!empty($data['messages'])) {
                            foreach ($data['messages'] as $m) {
                                $body['messages'][] = ['role' => $m['role'], 'content' => $m['content']];
                            }
                        }
                        return [
                                'url'     => 'https://api.anthropic.com/v1/messages',
                                'headers' => [
                                        'Content-Type: application/json',
                                        'x-api-key: '.$key,
                                        'anthropic-version: 2023-06-01',
                                ],
                                'body'    => json_encode($body),
                        ];
                    },
                    'parse' => function ($resp) {
                        $d = json_decode($resp, true);
                        $text = $d['content'][0]['text'] ?? null;
                        $err = $d['error']['message'] ?? null;
                        return ['text' => $text, 'error' => $err];
                    },
            ],
            'gemini' => [
                    'env'   => 'GEMINI_API_KEY',
                    'build' => function ($data, $key) {
                        $parts = [];
                        if (!empty($data['system'])) {
                            $parts[] = ['text' => $data['system']];
                        }
                        if (!empty($data['messages'])) {
                            foreach ($data['messages'] as $m) {
                                $parts[] = ['text' => $m['content']];
                            }
                        }
                        $body = [
                                'contents'         => [['parts' => $parts]],
                                'generationConfig' => ['maxOutputTokens' => 2048],
                        ];
                        if (!empty($data['system'])) {
                            $body['systemInstruction'] = ['parts' => [['text' => $data['system']]]];
                            $body['contents'] = [
                                    [
                                            'parts' => array_values(array_filter($parts, function ($p) use ($data) {
                                                return $p['text'] !== $data['system'];
                                            })),
                                    ],
                            ];
                        }
                        return [
                                'url'     => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key='.$key,
                                'headers' => ['Content-Type: application/json'],
                                'body'    => json_encode($body),
                        ];
                    },
                    'parse' => function ($resp) {
                        $d = json_decode($resp, true);
                        $text = $d['candidates'][0]['content']['parts'][0]['text'] ?? null;
                        $err = $d['error']['message'] ?? null;
                        $usage = $d['usageMetadata'] ?? null;
                        return ['text' => $text, 'error' => $err, 'usage' => $usage];
                    },
            ],
    ];

    // Leer keys y orden de prioridad del body JSON
    $clientKeys = isset($data['providers']) ? $data['providers'] : [];
    $order = isset($data['provider_order']) ? $data['provider_order'] : array_keys($PROVIDERS);

    // Resolver keys: client-sent > env var; filtrar proveedores sin key
    $resolved = [];
    foreach ($order as $pid) {
        if (!isset($PROVIDERS[$pid])) {
            continue;
        }
        $k = '';
        if (!empty($clientKeys[$pid])) {
            $k = $clientKeys[$pid];
        } elseif (!empty($CONFIG_KEYS[$pid])) {
            $k = $CONFIG_KEYS[$pid];
        } elseif (getenv($PROVIDERS[$pid]['env'])) {
            $k = getenv($PROVIDERS[$pid]['env']);
        }
        if ($k !== '') {
            $resolved[$pid] = $k;
        }
    }

    if (empty($resolved)) {
        header('Content-Type: application/json');
        http_response_code(401);
        echo json_encode(['error' => 'No hay proveedores configurados. Agregá al menos una API key.']);
        exit;
    }

    // Inyectar contexto de materiales del currículo (server-side)
    if (!empty($data['material_grade']) && !empty($data['material_subj'])) {
        $extra = build_default_ctx($data['material_grade'], $data['material_subj'], $DEFAULT_MATERIALS);
        if ($extra) {
            $data['system'] = (isset($data['system']) ? $data['system'] : '').$extra;
        }
    }

    // Capture cache fallback info before stripping control fields
    $fallbackCacheKey = isset($data['cache_key']) ? $data['cache_key'] : '';
    $fallbackExclude = isset($data['cache_exclude']) && is_array($data['cache_exclude']) ? $data['cache_exclude'] : [];

    // Debug-only: simulate error scenarios without breaking real providers.
    // Enable with env var PROFEBOT_DEBUG=1 + body JSON: {"_simulate":"ai_busy_no_cache"|"ai_busy_with_cache"}
    $simulate = (getenv('PROFEBOT_DEBUG') === '1' && !empty($data['_simulate'])) ? $data['_simulate'] : '';

    // Limpiar campos de control del body antes de enviar al proveedor
    unset($data['providers'], $data['provider_order'], $data['material_grade'], $data['material_subj'], $data['cache_key'], $data['cache_exclude'], $data['_simulate']);

    // Fallback loop
    $errors = [];
    $STOP_CODES = [400, 401]; // problemas de config, no reintentar
    $FALLBACK_CODES = [429, 402, 403, 500, 502, 503];

    header('Content-Type: application/json');
    header('Access-Control-Allow-Origin: *');

    if ($simulate === 'ai_busy_no_cache') {
        pb_log_warn('Simulating ai_busy_no_cache (forcing empty cache fallback)');
        $errors[] = 'simulated: all providers busy';
        $fallbackCacheKey = '__simulate_no_match__'; // guarantees cache miss
        goto cache_fallback;
    }
    if ($simulate === 'ai_busy_with_cache') {
        pb_log_warn('Simulating ai_busy_with_cache (forcing cache fallback path)');
        $errors[] = 'simulated: all providers busy';
        goto cache_fallback;
    }

    foreach ($resolved as $pid => $key) {
        $prov = $PROVIDERS[$pid];
        $req = $prov['build']($data, $key);

        $ch = curl_init($req['url']);
        curl_setopt_array($ch, [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST           => true,
                CURLOPT_POSTFIELDS     => $req['body'],
                CURLOPT_HTTPHEADER     => $req['headers'],
                CURLOPT_TIMEOUT        => 60,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => 0,
        ]);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlErr = curl_error($ch);
        curl_close($ch);

        // Error cURL → fallback
        if ($curlErr) {
            $errors[] = "$pid: red – $curlErr";
            pb_log_warn('Provider network error', ['provider' => $pid, 'curl_error' => $curlErr]);
            continue;
        }

        // HTTP error → decidir si parar o fallback
        if ($httpCode >= 400) {
            $parsed = $prov['parse']($response);
            $msg = $parsed['error'] ?: "HTTP $httpCode";
            if (in_array($httpCode, $STOP_CODES)) {
                pb_log_error('Provider config error (stop)', [
                    'provider' => $pid,
                    'http_code' => $httpCode,
                    'message' => $msg,
                    'raw' => substr((string)$response, 0, 1000),
                ]);
                http_response_code($httpCode);
                echo json_encode(['error' => "$pid: $msg", 'provider' => $pid]);
                exit;
            }
            $errors[] = "$pid: $msg";
            pb_log_warn('Provider HTTP error (fallback)', [
                'provider' => $pid,
                'http_code' => $httpCode,
                'message' => $msg,
                'raw' => substr((string)$response, 0, 1000),
            ]);
            continue; // fallback
        }

        // Éxito → parsear y devolver
        $parsed = $prov['parse']($response);
        if ($parsed['text']) {
            $out = ['content' => [['text' => $parsed['text']]], 'provider' => $pid];
            if (!empty($parsed['usage'])) {
                $out['usage'] = $parsed['usage'];
            }
            echo json_encode($out, JSON_UNESCAPED_UNICODE);
            exit;
        }
        $errors[] = "$pid: respuesta vacía";
        pb_log_warn('Provider empty response', ['provider' => $pid]);
    }

    // All providers failed → last resort: cache (progressive widening search)
    cache_fallback:
    pb_log_error('All providers failed', ['errors' => $errors, 'cache_key' => $fallbackCacheKey]);

    $cacheHit = null;
    $cacheMatchType = '';
    if ($fallbackCacheKey) {
        $cache = cache_read();
        $excludeFn = function ($q) use ($fallbackExclude) {
            return !in_array($q['question'], $fallbackExclude);
        };

        // 1) Exact cache_key match
        if (isset($cache[$fallbackCacheKey])) {
            $pool = array_values(array_filter($cache[$fallbackCacheKey], $excludeFn));
            if (!empty($pool)) {
                $cacheHit = $pool[array_rand($pool)];
                $cacheMatchType = 'exact';
            }
        }

        // 2) Widening: same grade::subj::idx (any difficulty)
        if (!$cacheHit) {
            $parts = explode('::', $fallbackCacheKey);
            // Last two parts are idx::difficulty → drop difficulty
            if (count($parts) >= 2) {
                $prefixWithoutDiff = implode('::', array_slice($parts, 0, count($parts) - 1));
                $pool = [];
                foreach ($cache as $k => $items) {
                    if (strpos($k, $prefixWithoutDiff.'::') === 0) {
                        $pool = array_merge($pool, array_filter($items, $excludeFn));
                    }
                }
                $pool = array_values($pool);
                if (!empty($pool)) {
                    $cacheHit = $pool[array_rand($pool)];
                    $cacheMatchType = 'same_objective';
                }
            }
        }

        // 3) Widening: same grade::subj (any objective and difficulty)
        if (!$cacheHit) {
            $parts = explode('::', $fallbackCacheKey);
            // grade::subj is usually the first 2 parts (format 1ro::mat::0::fácil) or just the first (mat::0::0::fácil legacy)
            $prefixSubj = count($parts) >= 4 ? $parts[0].'::'.$parts[1] : $parts[0];
            $pool = [];
            foreach ($cache as $k => $items) {
                if (strpos($k, $prefixSubj.'::') === 0) {
                    $pool = array_merge($pool, array_filter($items, $excludeFn));
                }
            }
            $pool = array_values($pool);
            if (!empty($pool)) {
                $cacheHit = $pool[array_rand($pool)];
                $cacheMatchType = 'same_subject';
            }
        }
    }

    if ($cacheHit) {
        pb_log_info('Cache fallback served', ['cache_key' => $fallbackCacheKey, 'match' => $cacheMatchType]);
        $warningKid = '¡Hoy juego con preguntas guardadas! Mi cerebro mágico está descansando.';
        $warning = 'El servicio de IA está saturado. Usando una pregunta del caché.';
        echo json_encode([
            'cached' => true,
            'question' => $cacheHit,
            'provider' => 'cache_fallback',
            'warning' => $warning,
            'warning_kid' => $warningKid,
        ], JSON_UNESCAPED_UNICODE);
        exit;
    }

    pb_log_error('Cache fallback empty', ['cache_key' => $fallbackCacheKey]);
    http_response_code(502);
    echo json_encode([
        'code' => 'AI_BUSY_NO_CACHE',
        'error' => 'El servicio de IA está ocupado y todavía no hay preguntas guardadas para este tema. Tocá Reintentar.',
        'error_kid' => '¡Ay! Mi cerebro mágico está pensando muy fuerte. Vamos a tocar el botón grande y probamos otra vez juntos.',
    ]);
    exit;
}

// ── OPTIONS (preflight) ──
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: POST, GET, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type');
    exit;
}

// ── GET → servir el HTML ──
$pb_version_js = htmlspecialchars(pb_version(), ENT_QUOTES, 'UTF-8');
echo "<!-- ProfeBot ".$pb_version_js." -->\n";
echo "<script>window.APP_VERSION=".json_encode(pb_version()).";</script>\n";
include __DIR__.'/profebot.html';
