<?php
// ═══════════════════════════════════════════════════════
//  ProfeBot — Local PHP server
//  Usage: php -S localhost:8080
//  Open: http://localhost:8080/profebot.php
// ═══════════════════════════════════════════════════════

// Error handling defaults. log_errors keeps every error visible in stderr
// (php -S console / Render logs). display_errors stays OFF by default because
// HTML-formatted PHP errors get prepended to JSON replies and break the client
// `r.json()` ("Unexpected token '<'"). It can be opted back in for local
// debugging via PROFEBOT_DISPLAY_ERRORS=1 (applied after .env loads, below).
ini_set('html_errors', '0');
ini_set('log_errors', '1');
ini_set('display_errors', '0');

// Autoloader (Monolog for logs). vendor/ is generated by `composer install`.
@require_once __DIR__.'/vendor/autoload.php';

use Monolog\Logger;
use Monolog\Handler\StreamHandler;

// ── QUESTION CACHE ──
define('CACHE_FILE', __DIR__.'/question_cache.json');
define('CACHE_MAX_PER_KEY', 50);

// ── VERSION ──
function pb_version()
{
    static $v = null;
    if ($v !== null) {
        return $v;
    }
    $f = __DIR__.'/VERSION';
    if (is_file($f)) {
        $v = trim(file_get_contents($f));
        if ($v !== '') {
            return $v;
        }
    }
    $v = 'dev';
    return $v;
}

// ── LOGGER ──
function pb_log()
{
    static $logger = null;
    if ($logger !== null) {
        return $logger;
    }
    if (!class_exists('Monolog\\Logger')) {
        $logger = false; // marker: Monolog not available
        return $logger;
    }
    $logger = new Logger('profebot');
    $logger->pushHandler(new StreamHandler('php://stderr', Logger::DEBUG));
    return $logger;
}

function pb_log_warn($msg, array $ctx = [])
{
    $l = pb_log();
    if ($l) {
        $l->warning($msg, $ctx);
    } else {
        error_log('[WARN] '.$msg.' '.json_encode($ctx, JSON_UNESCAPED_UNICODE));
    }
}

function pb_log_error($msg, array $ctx = [])
{
    $l = pb_log();
    if ($l) {
        $l->error($msg, $ctx);
    } else {
        error_log('[ERROR] '.$msg.' '.json_encode($ctx, JSON_UNESCAPED_UNICODE));
    }
}

function pb_log_info($msg, array $ctx = [])
{
    $l = pb_log();
    if ($l) {
        $l->info($msg, $ctx);
    } else {
        error_log('[INFO] '.$msg.' '.json_encode($ctx, JSON_UNESCAPED_UNICODE));
    }
}

// ── MATERIALS (server-side read; never exposed via HTTP) ──
define('MATERIALS_DIR', __DIR__.'/materiales');
// Total char budget per request (split across matched materials).
// Replaces the legacy per-file MATERIAL_MAX_CHARS limit.
define('MATERIAL_BUDGET_CHARS', 8000);

// Each entry may declare `units` as a list of unit indices (matching the
// JS GRADES[grade].subjects[subj].units order) it applies to. Omit `units`
// to mean "applies to every unit of that grade/subject" (back-compat for
// 1ro textbooks that span the whole curriculum).
$DEFAULT_MATERIALS = [
    ['file' => 'leng_libro_antiguo.txt', 'name' => 'Libro Lengua (antiguo)', 'subj' => 'leng', 'grade' => '1ro'],
    ['file' => 'leng_libro.txt', 'name' => '¡A leer! 1er. Grado', 'subj' => 'leng', 'grade' => '1ro'],
    ['file' => 'leng_cuaderno.txt', 'name' => 'Cuaderno Escritura', 'subj' => 'leng', 'grade' => '1ro'],
    ['file' => 'mat_libro_antiguo.txt', 'name' => 'Libro Matemática (antiguo)', 'subj' => 'mat', 'grade' => '1ro'],
    ['file' => 'mat_libro.txt', 'name' => 'Matemática 1er. Grado', 'subj' => 'mat', 'grade' => '1ro'],
    ['file' => 'mat_cuaderno.txt', 'name' => 'Cuaderno Matemática', 'subj' => 'mat', 'grade' => '1ro'],
    ['file' => 'preesc_mat_conjuntos.txt', 'name' => 'Nociones Matemáticas: Conjuntos (5to)', 'subj' => 'mat', 'grade' => 'preesc', 'units' => [0, 1, 2]],
    ['file' => 'preesc_mat_problemas.txt', 'name' => 'Solución de Problemas Sencillos (6to)', 'subj' => 'mat', 'grade' => 'preesc', 'units' => [4]],
    ['file' => 'preesc_mat_operaciones.txt', 'name' => 'Operaciones Combinadas de Conjuntos (6to)', 'subj' => 'mat', 'grade' => 'preesc', 'units' => [4]],
    ['file' => 'preesc_mat_longitudes.txt', 'name' => 'Trabajo con Longitudes (6to)', 'subj' => 'mat', 'grade' => 'preesc', 'units' => [3]],
    ['file' => 'preesc_len_fonico.txt', 'name' => 'Cuaderno de Análisis Fónico (6to)', 'subj' => 'len', 'grade' => 'preesc', 'units' => [0]],
    ['file' => 'preesc_len_cuentos.txt', 'name' => 'Cuentos para el 5to año de vida', 'subj' => 'len', 'grade' => 'preesc', 'units' => [1]],
    ['file' => 'preesc_len_poesias.txt', 'name' => 'Poesías para el 5to año de vida', 'subj' => 'len', 'grade' => 'preesc', 'units' => [3]],
    ['file' => 'preesc_len_adivinanzas.txt', 'name' => 'Adivinanzas 5to y 6to año', 'subj' => 'len', 'grade' => 'preesc', 'units' => [4]],
    ['file' => 'preesc_len_fabulas.txt', 'name' => 'Fábulas para el 5to año de vida', 'subj' => 'len', 'grade' => 'preesc', 'units' => [2]],
    ['file' => 'preesc_len_6to_cuentos.txt', 'name' => 'Cuentos para el 6to año de vida', 'subj' => 'len', 'grade' => 'preesc', 'units' => [1]],
    ['file' => 'preesc_len_6to_poesias.txt', 'name' => 'Poesías para el 6to año de vida', 'subj' => 'len', 'grade' => 'preesc', 'units' => [3]],
    ['file' => 'preesc_len_6to_fabulas.txt', 'name' => 'Fábulas para el 6to año de vida', 'subj' => 'len', 'grade' => 'preesc', 'units' => [2]],
    ['file' => 'preesc_len_trabalenguas.txt', 'name' => 'Trabalenguas para el 6to año de vida', 'subj' => 'len', 'grade' => 'preesc', 'units' => [4]],
];

function build_default_ctx($grade, $subj, $unit_idx, $materials)
{
    // Pass unit_idx === null to skip the unit filter (legacy behavior).
    $unit_int = ($unit_idx === null || $unit_idx === '') ? null : (int)$unit_idx;

    $matches = array_values(array_filter($materials, function ($m) use ($grade, $subj, $unit_int) {
        if ($m['grade'] !== $grade || $m['subj'] !== $subj) return false;
        if ($unit_int === null) return true;
        // No `units` key = applies to every unit (1ro textbooks span the whole curriculum).
        if (!isset($m['units']) || !is_array($m['units']) || empty($m['units'])) return true;
        return in_array($unit_int, $m['units'], true);
    }));
    if (empty($matches)) {
        pb_log_info('Materials ctx empty', ['grade' => $grade, 'subj' => $subj, 'unit_idx' => $unit_int]);
        return '';
    }

    // Distribute the global budget evenly across matched files.
    $per_file = (int) floor(MATERIAL_BUDGET_CHARS / count($matches));
    $ctx = "\n\n=== MATERIALES DEL CURRÍCULO ===\nUsá este contenido como guía para el nivel y estilo de las preguntas. Si el tema no aparece en el material, generá la pregunta igualmente basándote en el objetivo.\n\n";
    $i = 1;
    $total_chars = 0;
    $picked_files = [];
    foreach ($matches as $m) {
        $path = MATERIALS_DIR.'/'.$m['file'];
        if (!is_readable($path)) continue;
        $raw = @file_get_contents($path);
        if ($raw === false) continue;
        $content = trim($raw);
        if (function_exists('mb_substr')) {
            $content = mb_substr($content, 0, $per_file);
        } else {
            $content = substr($content, 0, $per_file);
        }
        $ctx .= "--- $i: ".substr($m['name'], 0, 50)." ---\n$content\n\n";
        $total_chars += strlen($content);
        $picked_files[] = $m['file'];
        $i++;
    }
    pb_log_info('Materials ctx built', [
        'grade'       => $grade,
        'subj'        => $subj,
        'unit_idx'    => $unit_int,
        'files'       => $picked_files,
        'per_file'    => $per_file,
        'total_chars' => $total_chars,
    ]);
    return $ctx."=== FIN ===\n";
}

// ── IMAGE INDEX (assets/img/_index.json, generated by tag_images.py) ──
define('IMAGE_INDEX_FILE', __DIR__.'/assets/img/_index.json');
define('IMAGE_PROMPT_MAX', 10); // cap items injected per request to keep prompt small

function image_index()
{
    static $index = null;
    if ($index !== null) return $index;
    if (!is_readable(IMAGE_INDEX_FILE)) {
        $index = [];
        return $index;
    }
    $raw = @file_get_contents(IMAGE_INDEX_FILE);
    $decoded = $raw ? json_decode($raw, true) : null;
    $index = is_array($decoded) ? $decoded : [];
    return $index;
}

function build_image_ctx($grade, $subj, $unit_idx)
{
    // Images currently only curated for preescolar.
    if ($grade !== 'preesc') return '';
    $unit_int = ($unit_idx === null || $unit_idx === '') ? null : (int)$unit_idx;

    $matches = array_values(array_filter(image_index(), function ($img) use ($subj, $unit_int) {
        if (empty($img['useful'])) return false;
        if (($img['subj'] ?? '') !== $subj) return false;
        if ($unit_int === null) return true;
        $units = $img['units'] ?? [];
        return is_array($units) && in_array($unit_int, $units, true);
    }));
    if (empty($matches)) return '';

    // Random sample to keep prompt small + add variety across calls.
    if (count($matches) > IMAGE_PROMPT_MAX) {
        $keys = array_rand($matches, IMAGE_PROMPT_MAX);
        $matches = array_map(fn($k) => $matches[$k], (array)$keys);
    }

    $ctx = "\n\n=== IMÁGENES DISPONIBLES PARA ESTA UNIDAD ===\n";
    $ctx .= "Si la pregunta lo requiere (ej: colores, formas, identificar personajes visualmente), podés mostrar UNA imagen agregando ANTES de la línea PREGUNTA esta línea exacta:\nIMAGEN: <ruta>\n";
    $ctx .= "Solo elegí entre estas rutas (no inventes ni modifiques nombres). Si ninguna calza con tu pregunta, NO uses IMAGEN.\n\n";
    foreach ($matches as $img) {
        $ctx .= "- ".$img['file']." — ".trim($img['description'] ?? '')."\n";
    }
    pb_log_info('Image ctx built', [
        'subj'     => $subj,
        'unit_idx' => $unit_int,
        'count'    => count($matches),
    ]);
    return $ctx."=== FIN IMÁGENES ===\n";
}

// Load .env if present (local php -S)
$CONFIG_KEYS = [];
if (file_exists(__DIR__ . '/.env')) {
    foreach (file(__DIR__ . '/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        if ($line[0] === '#' || strpos($line, '=') === false) continue;
        [$k, $v] = explode('=', $line, 2);
        putenv(trim($k) . '=' . trim($v));
    }
}
// Load config.php if present (InfinityFree or other hosting without env vars)
@include __DIR__ . '/config.php';

// Opt-in: also print PHP errors in the HTTP response. Local debugging only —
// this can corrupt JSON replies, so leave it off in production. Errors are
// already logged to stderr regardless (log_errors above).
if (getenv('PROFEBOT_DISPLAY_ERRORS') === '1') {
    ini_set('display_errors', '1');
}

// ── CACHE BACKEND ──
// If UPSTASH_REDIS_REST_URL + UPSTASH_REDIS_REST_TOKEN env vars are set,
// uses Upstash Redis (REST API via Guzzle). Otherwise falls back to a local
// JSON file (CACHE_FILE) for dev environments.
// Backend is selected once per request via cache_backend() and memoized.
define('CACHE_KEY_PREFIX', 'profebot:cache:');

function cache_backend()
{
    static $backend = null;
    if ($backend !== null) {
        return $backend;
    }
    $url = getenv('UPSTASH_REDIS_REST_URL');
    $token = getenv('UPSTASH_REDIS_REST_TOKEN');
    if ($url && $token && class_exists('GuzzleHttp\\Client')) {
        $backend = 'upstash';
    } else {
        $backend = 'file';
    }
    return $backend;
}

function upstash_client()
{
    static $client = null;
    if ($client !== null) {
        return $client;
    }
    $client = new GuzzleHttp\Client([
        'base_uri'        => rtrim(getenv('UPSTASH_REDIS_REST_URL'), '/').'/',
        'headers'         => [
            'Authorization' => 'Bearer '.getenv('UPSTASH_REDIS_REST_TOKEN'),
            'Content-Type'  => 'application/json',
        ],
        'timeout'         => 5.0,
        'connect_timeout' => 3.0,
        'http_errors'     => false,
    ]);
    return $client;
}

function upstash_cmd(array $command)
{
    try {
        $resp = upstash_client()->post('', ['json' => $command]);
        if ($resp->getStatusCode() >= 400) {
            pb_log_warn('Upstash HTTP error', [
                'status' => $resp->getStatusCode(),
                'cmd'    => $command[0] ?? '?',
                'body'   => substr((string)$resp->getBody(), 0, 300),
            ]);
            return null;
        }
        $body = json_decode((string)$resp->getBody(), true);
        return isset($body['result']) ? $body['result'] : null;
    } catch (\Throwable $e) {
        pb_log_warn('Upstash command failed', ['error' => $e->getMessage(), 'cmd' => $command[0] ?? '?']);
        return null;
    }
}

function upstash_pipeline(array $commands)
{
    if (empty($commands)) {
        return [];
    }
    try {
        $resp = upstash_client()->post('pipeline', ['json' => $commands]);
        if ($resp->getStatusCode() >= 400) {
            pb_log_warn('Upstash pipeline HTTP error', [
                'status' => $resp->getStatusCode(),
                'body'   => substr((string)$resp->getBody(), 0, 300),
            ]);
            return [];
        }
        $body = json_decode((string)$resp->getBody(), true);
        if (!is_array($body)) {
            return [];
        }
        return array_map(function ($r) {
            return isset($r['result']) ? $r['result'] : null;
        }, $body);
    } catch (\Throwable $e) {
        pb_log_warn('Upstash pipeline failed', ['error' => $e->getMessage()]);
        return [];
    }
}

function cache_read_file()
{
    if (!file_exists(CACHE_FILE)) {
        return [];
    }
    $raw = file_get_contents(CACHE_FILE);
    if ($raw === false || $raw === '') {
        return [];
    }
    $data = json_decode($raw, true);
    return is_array($data) ? $data : [];
}

function cache_write_file($data)
{
    $f = fopen(CACHE_FILE, 'c+');
    if (!$f) {
        return false;
    }
    flock($f, LOCK_EX);
    ftruncate($f, 0);
    rewind($f);
    fwrite($f, json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
    fflush($f);
    flock($f, LOCK_UN);
    fclose($f);
    return true;
}

function cache_get_key($key)
{
    if (cache_backend() === 'upstash') {
        $val = upstash_cmd(['GET', CACHE_KEY_PREFIX.$key]);
        if (!is_string($val)) {
            return [];
        }
        $decoded = json_decode($val, true);
        return is_array($decoded) ? $decoded : [];
    }
    $cache = cache_read_file();
    return isset($cache[$key]) ? $cache[$key] : [];
}

function cache_set_key($key, array $items)
{
    if (cache_backend() === 'upstash') {
        $val = json_encode($items, JSON_UNESCAPED_UNICODE);
        $res = upstash_cmd(['SET', CACHE_KEY_PREFIX.$key, $val]);
        return $res === 'OK';
    }
    $cache = cache_read_file();
    $cache[$key] = $items;
    return cache_write_file($cache);
}

// Returns [key => items[]] for cache keys starting with the given prefix.
// Used by the all-providers-failed fallback path for progressive widening.
function cache_scan_prefix($prefix)
{
    if (cache_backend() === 'upstash') {
        $pattern = CACHE_KEY_PREFIX.$prefix.'*';
        $cursor = '0';
        $keys = [];
        $iterations = 0;
        do {
            $res = upstash_cmd(['SCAN', $cursor, 'MATCH', $pattern, 'COUNT', '100']);
            if (!is_array($res) || count($res) < 2) {
                break;
            }
            $cursor = (string)$res[0];
            if (is_array($res[1])) {
                $keys = array_merge($keys, $res[1]);
            }
            $iterations++;
        } while ($cursor !== '0' && $iterations < 10 && count($keys) < 500);

        if (empty($keys)) {
            return [];
        }
        $cmds = array_map(function ($k) {
            return ['GET', $k];
        }, $keys);
        $values = upstash_pipeline($cmds);
        $out = [];
        foreach ($keys as $i => $fullKey) {
            $shortKey = substr($fullKey, strlen(CACHE_KEY_PREFIX));
            $val = isset($values[$i]) ? $values[$i] : null;
            if (!is_string($val)) {
                continue;
            }
            $decoded = json_decode($val, true);
            if (is_array($decoded)) {
                $out[$shortKey] = $decoded;
            }
        }
        return $out;
    }
    $cache = cache_read_file();
    $out = [];
    foreach ($cache as $k => $items) {
        if (strpos($k, $prefix) === 0) {
            $out[$k] = $items;
        }
    }
    return $out;
}

// ── API PROXY: multi-provider with automatic fallback ──
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $raw = file_get_contents('php://input');
    $data = json_decode($raw, true);

    // ── Cache actions ──
    if (isset($data['action'])) {
        header('Content-Type: application/json');
        header('Access-Control-Allow-Origin: *');

        if ($data['action'] === 'cache_get') {
            $key = isset($data['cache_key']) ? $data['cache_key'] : '';
            $exclude = isset($data['exclude']) ? $data['exclude'] : [];
            $items = cache_get_key($key);
            // Filter out already-asked questions
            $available = array_values(array_filter($items, function ($q) use ($exclude) {
                return !in_array($q['question'], $exclude);
            }));
            if (empty($available)) {
                echo json_encode(['cached' => false]);
            } else {
                // If fewer than 5 cached, 50% chance to skip cache and go to AI to grow variety
                if (count($items) < 5 && mt_rand(1, 100) <= 50) {
                    echo json_encode(['cached' => false]);
                } else {
                    $pick = $available[array_rand($available)];
                    echo json_encode(['cached' => true, 'question' => $pick]);
                }
            }
            exit;
        }

        if ($data['action'] === 'materials_meta') {
            $grade = isset($data['grade']) ? $data['grade'] : '';
            $list = array_values(array_filter($DEFAULT_MATERIALS, function ($m) use ($grade) {
                return !$grade || $m['grade'] === $grade;
            }));
            $out = array_map(function ($m) {
                return ['name' => $m['name'], 'subj' => $m['subj'], 'grade' => $m['grade']];
            }, $list);
            echo json_encode(['materials' => $out], JSON_UNESCAPED_UNICODE);
            exit;
        }

        if ($data['action'] === 'cache_save') {
            $key = isset($data['cache_key']) ? $data['cache_key'] : '';
            $question = isset($data['question']) ? $data['question'] : null;
            if (!$key || !$question) {
                echo json_encode(['saved' => false, 'error' => 'missing data']);
                exit;
            }
            $items = cache_get_key($key);
            $items[] = $question;
            // FIFO: keep max per key
            if (count($items) > CACHE_MAX_PER_KEY) {
                $items = array_slice($items, -CACHE_MAX_PER_KEY);
            }
            $ok = cache_set_key($key, $items);
            echo json_encode(['saved' => $ok]);
            exit;
        }
    }

    // Provider registry
    $PROVIDERS = [
            // OpenRouter (OpenAI-compatible). Listed first so it serves before the
            // direct Gemini call, which is geo-blocked from datacenter IPs (e.g. Render).
            // Free :free models bypass that block because OpenRouter calls the upstream,
            // not our server. Swap the model string to try other free models — check the
            // live list at https://openrouter.ai/api/v1/models (filter pricing.prompt=="0"),
            // e.g. 'qwen/qwen3-next-80b-a3b-instruct:free'. Avoid reasoning models (R1):
            // their thinking tokens break the strict 7-line parseQ format.
            'openrouter' => [
                    'env'   => 'OPENROUTER_API_KEY',
                    'build' => function ($data, $key) {
                        $model = 'deepseek/deepseek-v4-flash:free';
                        $body = ['model' => $model, 'max_tokens' => 2048, 'messages' => []];
                        if (!empty($data['system'])) {
                            $body['messages'][] = ['role' => 'system', 'content' => $data['system']];
                        }
                        if (!empty($data['messages'])) {
                            foreach ($data['messages'] as $m) {
                                $body['messages'][] = ['role' => $m['role'], 'content' => $m['content']];
                            }
                        }
                        return [
                                'url'     => 'https://openrouter.ai/api/v1/chat/completions',
                                'headers' => [
                                        'Content-Type: application/json',
                                        'Authorization: Bearer '.$key,
                                        'X-Title: ProfeBot',
                                ],
                                'body'    => json_encode($body),
                        ];
                    },
                    'parse' => function ($resp) {
                        $d = json_decode($resp, true);
                        $text = $d['choices'][0]['message']['content'] ?? null;
                        $err = $d['error']['message'] ?? null;
                        $usage = $d['usage'] ?? null;
                        return ['text' => $text, 'error' => $err, 'usage' => $usage];
                    },
            ],
            'groq'   => [
                    'env'   => 'GROQ_API_KEY',
                    'build' => function ($data, $key) {
                        $body = ['model' => 'llama-3.3-70b-versatile', 'max_tokens' => 2048, 'messages' => []];
                        if (!empty($data['system'])) {
                            $body['messages'][] = ['role' => 'system', 'content' => $data['system']];
                        }
                        if (!empty($data['messages'])) {
                            foreach ($data['messages'] as $m) {
                                $body['messages'][] = ['role' => $m['role'], 'content' => $m['content']];
                            }
                        }
                        return [
                                'url'     => 'https://api.groq.com/openai/v1/chat/completions',
                                'headers' => ['Content-Type: application/json', 'Authorization: Bearer '.$key],
                                'body'    => json_encode($body),
                        ];
                    },
                    'parse' => function ($resp) {
                        $d = json_decode($resp, true);
                        $text = $d['choices'][0]['message']['content'] ?? null;
                        $err = $d['error']['message'] ?? null;
                        $usage = $d['usage'] ?? null;
                        return ['text' => $text, 'error' => $err, 'usage' => $usage];
                    },
            ],
            'claude' => [
                    'env'   => 'ANTHROPIC_API_KEY',
                    'build' => function ($data, $key) {
                        $body = ['model' => 'claude-sonnet-4-20250514', 'max_tokens' => 1024];
                        if (!empty($data['system'])) {
                            $body['system'] = $data['system'];
                        }
                        $body['messages'] = [];
                        if (!empty($data['messages'])) {
                            foreach ($data['messages'] as $m) {
                                $body['messages'][] = ['role' => $m['role'], 'content' => $m['content']];
                            }
                        }
                        return [
                                'url'     => 'https://api.anthropic.com/v1/messages',
                                'headers' => [
                                        'Content-Type: application/json',
                                        'x-api-key: '.$key,
                                        'anthropic-version: 2023-06-01',
                                ],
                                'body'    => json_encode($body),
                        ];
                    },
                    'parse' => function ($resp) {
                        $d = json_decode($resp, true);
                        $text = $d['content'][0]['text'] ?? null;
                        $err = $d['error']['message'] ?? null;
                        $usage = $d['usage'] ?? null;
                        return ['text' => $text, 'error' => $err, 'usage' => $usage];
                    },
            ],
            'gemini' => [
                    'env'   => 'GEMINI_API_KEY',
                    'build' => function ($data, $key) {
                        $parts = [];
                        if (!empty($data['system'])) {
                            $parts[] = ['text' => $data['system']];
                        }
                        if (!empty($data['messages'])) {
                            foreach ($data['messages'] as $m) {
                                $parts[] = ['text' => $m['content']];
                            }
                        }
                        $body = [
                                'contents'         => [['parts' => $parts]],
                                'generationConfig' => ['maxOutputTokens' => 2048],
                        ];
                        if (!empty($data['system'])) {
                            $body['systemInstruction'] = ['parts' => [['text' => $data['system']]]];
                            $body['contents'] = [
                                    [
                                            'parts' => array_values(array_filter($parts, function ($p) use ($data) {
                                                return $p['text'] !== $data['system'];
                                            })),
                                    ],
                            ];
                        }
                        return [
                                'url'     => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key='.$key,
                                'headers' => ['Content-Type: application/json'],
                                'body'    => json_encode($body),
                        ];
                    },
                    'parse' => function ($resp) {
                        $d = json_decode($resp, true);
                        $text = $d['candidates'][0]['content']['parts'][0]['text'] ?? null;
                        $err = $d['error']['message'] ?? null;
                        $usage = $d['usageMetadata'] ?? null;
                        return ['text' => $text, 'error' => $err, 'usage' => $usage];
                    },
            ],
    ];

    // Read keys and priority order from JSON body
    $clientKeys = isset($data['providers']) ? $data['providers'] : [];
    $order = isset($data['provider_order']) ? $data['provider_order'] : array_keys($PROVIDERS);

    // Resolve keys: client-sent > env var; filter providers without key
    $resolved = [];
    foreach ($order as $pid) {
        if (!isset($PROVIDERS[$pid])) {
            continue;
        }
        $k = '';
        if (!empty($clientKeys[$pid])) {
            $k = $clientKeys[$pid];
        } elseif (!empty($CONFIG_KEYS[$pid])) {
            $k = $CONFIG_KEYS[$pid];
        } elseif (getenv($PROVIDERS[$pid]['env'])) {
            $k = getenv($PROVIDERS[$pid]['env']);
        }
        if ($k !== '') {
            $resolved[$pid] = $k;
        }
    }

    if (empty($resolved)) {
        header('Content-Type: application/json');
        http_response_code(401);
        echo json_encode(['error' => 'No hay proveedores configurados. Agregá al menos una API key.']);
        exit;
    }

    // Inject curriculum materials context (server-side)
    $materials_chars = 0;
    $images_chars = 0;
    if (!empty($data['material_grade']) && !empty($data['material_subj'])) {
        $unit_idx = isset($data['material_unit_idx']) ? $data['material_unit_idx'] : null;
        $extra = build_default_ctx($data['material_grade'], $data['material_subj'], $unit_idx, $DEFAULT_MATERIALS);
        if ($extra) {
            $data['system'] = (isset($data['system']) ? $data['system'] : '').$extra;
            $materials_chars = strlen($extra);
        }
        $imgCtx = build_image_ctx($data['material_grade'], $data['material_subj'], $unit_idx);
        if ($imgCtx) {
            $data['system'] = (isset($data['system']) ? $data['system'] : '').$imgCtx;
            $images_chars = strlen($imgCtx);
        }
    }

    // Capture cache fallback info before stripping control fields
    $fallbackCacheKey = isset($data['cache_key']) ? $data['cache_key'] : '';
    $fallbackExclude = isset($data['cache_exclude']) && is_array($data['cache_exclude']) ? $data['cache_exclude'] : [];

    // Debug-only: simulate error scenarios without breaking real providers.
    // Enable with env var PROFEBOT_DEBUG=1 + body JSON: {"_simulate":"ai_busy_no_cache"|"ai_busy_with_cache"}
    $simulate = (getenv('PROFEBOT_DEBUG') === '1' && !empty($data['_simulate'])) ? $data['_simulate'] : '';

    // Strip control fields from body before sending to provider
    unset($data['providers'], $data['provider_order'], $data['material_grade'], $data['material_subj'], $data['material_unit_idx'], $data['cache_key'], $data['cache_exclude'], $data['_simulate']);

    // Fallback loop
    $errors = [];
    $stopError = null; // remembers a config error (400/401) to surface if nothing else works
    $STOP_CODES = [400, 401]; // config errors, do not retry the SAME provider
    $FALLBACK_CODES = [429, 402, 403, 500, 502, 503];

    header('Content-Type: application/json');
    header('Access-Control-Allow-Origin: *');

    if ($simulate === 'ai_busy_no_cache') {
        pb_log_warn('Simulating ai_busy_no_cache (forcing empty cache fallback)');
        $errors[] = 'simulated: all providers busy';
        $fallbackCacheKey = '__simulate_no_match__'; // guarantees cache miss
        goto cache_fallback;
    }
    if ($simulate === 'ai_busy_with_cache') {
        pb_log_warn('Simulating ai_busy_with_cache (forcing cache fallback path)');
        $errors[] = 'simulated: all providers busy';
        goto cache_fallback;
    }

    foreach ($resolved as $pid => $key) {
        $prov = $PROVIDERS[$pid];
        $req = $prov['build']($data, $key);

        $ch = curl_init($req['url']);
        curl_setopt_array($ch, [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST           => true,
                CURLOPT_POSTFIELDS     => $req['body'],
                CURLOPT_HTTPHEADER     => $req['headers'],
                CURLOPT_TIMEOUT        => 60,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => 0,
        ]);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlErr = curl_error($ch);
        curl_close($ch);

        // Error cURL → fallback
        if ($curlErr) {
            $errors[] = "$pid: red – $curlErr";
            pb_log_warn('Provider network error', ['provider' => $pid, 'curl_error' => $curlErr]);
            continue;
        }

        // HTTP error → decide whether to stop or fallback
        if ($httpCode >= 400) {
            $parsed = $prov['parse']($response);
            $msg = $parsed['error'] ?: "HTTP $httpCode";
            $errors[] = "$pid: $msg";
            if (in_array($httpCode, $STOP_CODES)) {
                // Config error (bad key, unsupported request). Don't retry this provider,
                // but keep trying the rest of the chain — another provider may still work.
                // E.g. Gemini geo-block returns 400 ("User location is not supported") on
                // Render even though Groq is fine. Remember it to surface a precise message
                // only if every provider (and the cache) fails.
                $stopError = ['code' => $httpCode, 'msg' => "$pid: $msg", 'provider' => $pid];
                pb_log_warn('Provider config error (skip, try next)', [
                    'provider' => $pid,
                    'http_code' => $httpCode,
                    'message' => $msg,
                    'raw' => substr((string)$response, 0, 1000),
                ]);
                continue;
            }
            pb_log_warn('Provider HTTP error (fallback)', [
                'provider' => $pid,
                'http_code' => $httpCode,
                'message' => $msg,
                'raw' => substr((string)$response, 0, 1000),
            ]);
            continue; // fallback
        }

        // Success → parse and return
        $parsed = $prov['parse']($response);
        if ($parsed['text']) {
            $userChars = 0;
            foreach (($data['messages'] ?? []) as $m) {
                $userChars += strlen($m['content'] ?? '');
            }
            $out = [
                'content'  => [['text' => $parsed['text']]],
                'provider' => $pid,
                'stats'    => [
                    'system_chars'    => strlen($data['system'] ?? ''),
                    'user_chars'      => $userChars,
                    'materials_chars' => $materials_chars,
                    'images_chars'    => $images_chars,
                ],
            ];
            if (!empty($parsed['usage'])) {
                $out['usage'] = $parsed['usage'];
            }
            echo json_encode($out, JSON_UNESCAPED_UNICODE);
            exit;
        }
        $errors[] = "$pid: respuesta vacía";
        pb_log_warn('Provider empty response', ['provider' => $pid]);
    }

    // All providers failed → last resort: cache (progressive widening search)
    cache_fallback:
    pb_log_error('All providers failed', ['errors' => $errors, 'cache_key' => $fallbackCacheKey]);

    $cacheHit = null;
    $cacheMatchType = '';
    if ($fallbackCacheKey) {
        $excludeFn = function ($q) use ($fallbackExclude) {
            return !in_array($q['question'], $fallbackExclude);
        };

        // 1) Exact cache_key match
        $exactItems = cache_get_key($fallbackCacheKey);
        if (!empty($exactItems)) {
            $pool = array_values(array_filter($exactItems, $excludeFn));
            if (!empty($pool)) {
                $cacheHit = $pool[array_rand($pool)];
                $cacheMatchType = 'exact';
            }
        }

        // 2) Widening: same grade::subj::idx (any difficulty)
        if (!$cacheHit) {
            $parts = explode('::', $fallbackCacheKey);
            // Last component is difficulty → drop it
            if (count($parts) >= 2) {
                $prefixWithoutDiff = implode('::', array_slice($parts, 0, count($parts) - 1)).'::';
                $matches = cache_scan_prefix($prefixWithoutDiff);
                $pool = [];
                foreach ($matches as $items) {
                    $pool = array_merge($pool, array_filter($items, $excludeFn));
                }
                $pool = array_values($pool);
                if (!empty($pool)) {
                    $cacheHit = $pool[array_rand($pool)];
                    $cacheMatchType = 'same_objective';
                }
            }
        }

        // 3) Widening: same grade::subj (any objective and difficulty)
        if (!$cacheHit) {
            $parts = explode('::', $fallbackCacheKey);
            // grade::subj is the first 2 parts in current format (1ro::mat::U::O::diff) or just the first in legacy (mat::U::O::diff)
            $prefixSubj = (count($parts) >= 4 ? $parts[0].'::'.$parts[1] : $parts[0]).'::';
            $matches = cache_scan_prefix($prefixSubj);
            $pool = [];
            foreach ($matches as $items) {
                $pool = array_merge($pool, array_filter($items, $excludeFn));
            }
            $pool = array_values($pool);
            if (!empty($pool)) {
                $cacheHit = $pool[array_rand($pool)];
                $cacheMatchType = 'same_subject';
            }
        }
    }

    if ($cacheHit) {
        pb_log_info('Cache fallback served', ['cache_key' => $fallbackCacheKey, 'match' => $cacheMatchType]);
        $warningKid = '¡Hoy juego con preguntas guardadas! Mi cerebro mágico está descansando.';
        $warning = 'El servicio de IA está saturado. Usando una pregunta del caché.';
        echo json_encode([
            'cached' => true,
            'question' => $cacheHit,
            'provider' => 'cache_fallback',
            'warning' => $warning,
            'warning_kid' => $warningKid,
        ], JSON_UNESCAPED_UNICODE);
        exit;
    }

    pb_log_error('Cache fallback empty', ['cache_key' => $fallbackCacheKey]);
    // If a provider hit a config error (e.g. bad key with a single provider) and nothing
    // else worked, surface that precise message instead of the generic "AI busy" one.
    if ($stopError) {
        http_response_code($stopError['code']);
        echo json_encode(['error' => $stopError['msg'], 'provider' => $stopError['provider']]);
        exit;
    }
    http_response_code(502);
    echo json_encode([
        'code' => 'AI_BUSY_NO_CACHE',
        'error' => 'El servicio de IA está ocupado y todavía no hay preguntas guardadas para este tema. Tocá Reintentar.',
        'error_kid' => '¡Ay! Mi cerebro mágico está pensando muy fuerte. Vamos a tocar el botón grande y probamos otra vez juntos.',
    ]);
    exit;
}

// ── OPTIONS (preflight) ──
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: POST, GET, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type');
    exit;
}

// ── GET → serve HTML ──
$pb_version_js = htmlspecialchars(pb_version(), ENT_QUOTES, 'UTF-8');
echo "<!-- ProfeBot ".$pb_version_js." -->\n";
echo "<script>window.APP_VERSION=".json_encode(pb_version()).";</script>\n";
include __DIR__.'/profebot.html';
